name: Python Test Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Diese virtuelle Maschine wird verwendet

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3  # Klont das Repository

    - name: Set up Python
      uses: actions/setup-python@v3  # Installiert Python
      with:
        python-version: '3.x'  # Wählt die Python-Version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r  requirements.txt # Installiert Abhängigkeiten (aus requirements.txt)

    - name: Run tests
      run: |
        pytest  # Führt pytest aus, um Tests zu starten
